nelmio_security:
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY
    csp:
        hosts: []
        content_types: []
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            report-uri: null
            default-src:
                - 'none'
            script-src:
                - 'self'
                - "'unsafe-inline'"
                - 'https://cdn.jsdelivr.net'
            connect-src:
                - 'self'
                - 'http://localhost:3000'
            style-src:
                - 'self'
                - "'unsafe-inline'"
                - 'https://cdn.jsdelivr.net'
            img-src:
                - 'self'
                - 'https://cdn.jsdelivr.net'



            block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
            # upgrade-insecure-requests: true # defaults to false, upgrades HTTP requests to HTTPS transport

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
